name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage
        
    - name: Run tests
      run: |
        python -m pytest src/unit_tests/
        
    - name: Calculate test coverage
      run: |
        python -m coverage run -m pytest src/unit_tests/
        python -m coverage report
        python -m coverage html
        
    - name: Prepare data
      run: |
        mkdir -p data
        mkdir -p experiments
        python src/preprocess.py
        
    - name: Train model
      run: |
        python src/train.py
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/penguin-classifier:latest,${{ secrets.DOCKERHUB_USERNAME }}/penguin-classifier:${{ github.sha }}
        
    - name: Update dev_sec_ops.yml
      if: github.event_name != 'pull_request'
      run: |
        # Get Docker image digest
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKERHUB_USERNAME }}/penguin-classifier:latest | cut -d'@' -f2)
        
        # Get last 5 commit hashes
        COMMITS=$(git log -5 --pretty=format:"%H %s")
        
        # Update dev_sec_ops.yml with the new digest and commits
        sed -i "s|digest: sha256:.*|digest: $DIGEST|" dev_sec_ops.yml
        
        # Get test coverage
        COVERAGE=$(python -m coverage report | grep TOTAL | awk '{print $NF}')
        sed -i "s|total: .*%|total: $COVERAGE|" dev_sec_ops.yml
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-and-reports
        path: |
          experiments/
          htmlcov/
          dev_sec_ops.yml 